
name: Build

on:
  push:
    paths:
      - .github/workflows/main.yml
      - valheim-hax/**

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build valheim-hax
      run: dotnet build valheim-hax
